{
  "comments": [
    {
      "key": {
        "uuid": "febe8864_db7ea1a1",
        "filename": "test/hash_test.cc",
        "patchSetId": 2
      },
      "lineNbr": 127,
      "author": {
        "id": 5020
      },
      "writtenOn": "2018-03-02T06:50:27Z",
      "side": 1,
      "message": "add an ASSERT_TRUE(buffer_ !\u003d NULL) here",
      "revId": "1f06402aa19003a9fcc273dcdaab777adeccb99b",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "1e19bdac_ed9553c1",
        "filename": "test/hash_test.cc",
        "patchSetId": 2
      },
      "lineNbr": 127,
      "author": {
        "id": 8900
      },
      "writtenOn": "2018-03-02T07:02:28Z",
      "side": 1,
      "message": "On failure \"new\" through an exception, the following ASSERT_TRUE will never be hit.\n\nhttps://stackoverflow.com/questions/26419786/why-doesnt-new-in-c-return-null-on-failure",
      "parentUuid": "febe8864_db7ea1a1",
      "revId": "1f06402aa19003a9fcc273dcdaab777adeccb99b",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0",
      "unresolved": true
    }
  ]
}