{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "15ba3ae9_6f93634f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 9545
      },
      "writtenOn": "2022-09-14T23:20:11Z",
      "side": 1,
      "message": "This is another small improvement to error reporting. I didn\u0027t try to forward the error message set by the previous aom_internal_error() call in this CL. I only forward the error code.",
      "revId": "422e923fa02f6b267d2b99df2020fdb90fe3cae3",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "a46d6e26_d1c33240",
        "filename": "av1/av1_cx_iface.c",
        "patchSetId": 1
      },
      "lineNbr": 3043,
      "author": {
        "id": 9545
      },
      "writtenOn": "2024-03-13T16:58:30Z",
      "side": 1,
      "message": "This line now reads:\n\n```\n        aom_internal_error_copy(\u0026ppi-\u003eerror, cpi-\u003ecommon.error);\n```",
      "revId": "422e923fa02f6b267d2b99df2020fdb90fe3cae3",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    }
  ]
}