{
  "comments": [
    {
      "key": {
        "uuid": "cadaf69f_3a2c14ff",
        "filename": "av1/decoder/decodemv.c",
        "patchSetId": 3
      },
      "lineNbr": 743,
      "author": {
        "id": 9545
      },
      "writtenOn": "2019-01-28T19:43:57Z",
      "side": 1,
      "message": "If it is safe to call aom_internal_error() here, can we just call aom_internal_error()?",
      "range": {
        "startLine": 741,
        "startChar": 0,
        "endLine": 743,
        "endChar": 65
      },
      "revId": "48b854a10c54c24b5411ba82d0d21baa0abf65b7",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0",
      "unresolved": true
    }
  ]
}