{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "4b8af5ee_f47cb219",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 18227
      },
      "writtenOn": "2021-03-05T05:20:32Z",
      "side": 1,
      "message": "From the below error message:\n\nERROR: Error cloning remote repo \u0027origin\u0027\n\nSeems that the build failure is not because of the code patch. \n\nPlease take a look. @Urvang",
      "revId": "8108c59d594c9920012fb22046772102d2b67c2a",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    }
  ]
}