{
  "comments": [
    {
      "key": {
        "uuid": "244a4311_138e6295",
        "filename": "av1/decoder/decodeframe.c",
        "patchSetId": 1
      },
      "lineNbr": 5069,
      "author": {
        "id": 9545
      },
      "writtenOn": "2018-10-03T18:54:49Z",
      "side": 1,
      "message": "This is the fix for the oss-fuzz bug. I audited all callers of get_free_fb() and found a similar bug in encoder.c, which I also fixed in this CL.",
      "revId": "9211514343d8d7c06466c6fb953e471d05977354",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fffcfc69_8b1aa447",
        "filename": "av1/encoder/encoder.c",
        "patchSetId": 1
      },
      "lineNbr": 3748,
      "author": {
        "id": 9545
      },
      "writtenOn": "2018-10-03T18:54:49Z",
      "side": 1,
      "message": "Note that force_scaling is true if and only if new_fb contains a new frame buffer reference returned by get_free_fb(). In this case, we must release that reference before calling aom_internal_error().",
      "range": {
        "startLine": 3743,
        "startChar": 0,
        "endLine": 3748,
        "endChar": 9
      },
      "revId": "9211514343d8d7c06466c6fb953e471d05977354",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "8b774d1a_4e94cac2",
        "filename": "av1/encoder/encoder.c",
        "patchSetId": 1
      },
      "lineNbr": 3761,
      "author": {
        "id": 9545
      },
      "writtenOn": "2018-10-03T18:54:49Z",
      "side": 1,
      "message": "Since new_fb may be an existing reference in cpi-\u003escaled_ref_idx[ref_frame - 1] (see line 3744), we should only release the reference on error if force_scaling is true.",
      "revId": "9211514343d8d7c06466c6fb953e471d05977354",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0",
      "unresolved": false
    }
  ]
}