{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "83b28b19_6d4daafe",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 5186
      },
      "writtenOn": "2021-08-20T19:45:32Z",
      "side": 1,
      "message": "Is this still causing an assert failure or is it ready? ",
      "revId": "98738a21988e8815e7ed255ee3598f73a0a5b873",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "995ad485_f6ad9a20",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 5189
      },
      "writtenOn": "2021-08-20T19:49:33Z",
      "side": 1,
      "message": "No - not yet ready. I am just beginning to debug the assert.",
      "parentUuid": "83b28b19_6d4daafe",
      "revId": "98738a21988e8815e7ed255ee3598f73a0a5b873",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    }
  ]
}