{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "fe27b7ff_ee6d4f2e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 22433
      },
      "writtenOn": "2021-02-24T13:56:35Z",
      "side": 1,
      "message": "Hi Wan-Teh,\n\nWe have taken care of the review comments, given by you in the latest patchset (Patchset 3) and the patch is ready for review.\n\nWe see that Jenkins build has not started for the latest patchset. When we tried re-triggering the build for patchset 2, the build failed with error message \"Error cloning the remote repo\".\nCan you help us in retriggering the Jenkins build for patchset 3.\n\nHi Hui Su,\nPlease review the patch.\n\nThanks \u0026 Regards, \nAniket\n",
      "revId": "b916cb17098ddfa0c19891359210b00fe547ad40",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "2b0180e8_7f7bc067",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 9545
      },
      "writtenOn": "2021-02-25T01:14:47Z",
      "side": 1,
      "message": "I just retriggered the Jenkins build for patchset 3.",
      "parentUuid": "fe27b7ff_ee6d4f2e",
      "revId": "b916cb17098ddfa0c19891359210b00fe547ad40",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    }
  ]
}