{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "a211f841_76dee379",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 5290
      },
      "writtenOn": "2021-05-04T15:36:53Z",
      "side": 1,
      "message": "\u003e Patch Set 9: Verified-1\n\u003e \n\u003e Build Failed \n\u003e \n\u003e https://build.aomedia.org/jenkins/job/libaom__commit_trigger/59553/ : FAILURE\n\nThis was due to network issues.\nRetriggered the tests.",
      "revId": "e6de70095d4e8420525b41b2f3d4b5079f3ae40a",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    }
  ]
}