{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "f9d1e53d_51f87828",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 31957
      },
      "writtenOn": "2023-09-19T12:37:18Z",
      "side": 1,
      "message": "Looks like the test failure was unrelated to the patch itself",
      "revId": "f4b10334f547bf379a8250f53e404cb96b995517",
      "serverId": "e5514cf8-2d6e-3e29-adb4-24cd6dde4bf0"
    }
  ]
}